version: '3.8'

services:
  app:
    build:
      context: ./docker/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    container_name: app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - redis
      - mongo_primary
  mongo_primary:
    container_name: mongo_primary
    image: mongo:4.4.7
    volumes:
      - ./docker/8.2/data1:/data/db
      - ./docker/8.2/key:/scripts/key
      - ./docker/8.2/rs-init.sh:/scripts/rs-init.sh
      - ./docker/8.2/createUser.sh:/scripts/createUser.sh
    networks:
      - sail
    ports:
      - 27021:27017
    depends_on:
        - mongo_secondary_1
        - mongo_secondary_2
    links:
      - mongo_secondary_1
      - mongo_secondary_2
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--keyFile", "/scripts/key" ]
  mongo_secondary_1:
    container_name: mongo_secondary_1
    image: mongo:4.4.7
    volumes:
      - ./docker/8.2/data2:/data/db
      - ./docker/8.2/key:/scripts/key
    networks:
      - sail
    ports:
      - 27022:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--keyFile", "/scripts/key" ]
  mongo_secondary_2:
      container_name: mongo_secondary_2
      image: mongo:4.4.7
      volumes:
          - ./docker/8.2/data3:/data/db
          - ./docker/8.2/key:/scripts/key
      networks:
          - sail
      ports:
          - 27023:27017
      restart: always
      entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--keyFile", "/scripts/key" ]
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge
volumes:
  sail-redis:
    driver: local
